### ISSUE TITLE
Running ffi-generate-node on libsbml

### ISSUE THREAD

**Issue by stanleygu** [tjfontaine/node-libclang#4]
I am trying to generate the appropriate bindings for [libsbml](http://sbml.org/Software/libSBML). However, when I run the following line:

``` bash
./node_modules/.bin/ffi-generate-node -f /usr/local/include/sbml/SBMLReader.h -l /usr/local/lib/libsbml.a
```

I get this error message:

``` bash
/node_modules/ffi/node_modules/bindings/bindings.js:79
        throw e
              ^
Error: dlopen(node_modules/ffi/node_modules/ref/build/Release/binding.node, 1): no suitable image found.  Did find:
    /node_modules/ffi/node_modules/ref/build/Release/binding.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
    at Object.Module._extensions..node (module.js:485:11)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at bindings (/node_modules/ffi/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/node_modules/ffi/node_modules/ref/lib/ref.js:5:47)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
```

**Comment by tjfontaine** [comment]
that's a scary error, I'm not entirely sure what's going on right there, but I can tell you that the `-l` argument should just be a name, not a path to the actual static library.

Did you happen to copy your node_modules from one computer to another?

**Comment by stanleygu** [comment]
I had cloned my project that was originally developed on linux over to osx, after I re-running `npm install libclang` I was able to get `ffi-generate-node` running okay. Thanks for your suggestion!

Would it best not to include node_modules in the repo to ensure that binaries are rebuilt?

**Comment by tjfontaine** [comment]
When you're dealing with projects that potentially have binary addon dependencies it's ideal not to pass your node_modules around, if you're in a pure javascript project you don't always have to adhere to such a rule.
